---
- hosts: dev-test
  name: package-checker
  become: yes
  vars: 
    package_names: 
    - figlet
  tasks: 
  - name: "Check if listed package is installed" 
    command: apt-list | grep {{ item }}
    loop: "{{ package_names }}"
    register package_check 
    when ansible_facts['os_family'] == "Debian"
  - name: "Print findings" 
    debug: 
      msg: "package is installed" 
    when: package_check is succeeded 