---
  - hosts: dev-test
    name: test command prompt change
    become: yes
    tasks:
     - name: insert command prompt change to bashrc
       lineinfile:
         path: /home/ubuntu/.bashrc
         line: PS1="\e[0;37m[prod_tf_controller@\h \W]\$ \e[0m"
     - name: source bashrc
       shell: source /home/ubuntu/.bashrc && source ~/.bashrc
       args:
         executable: /bin/bash
