---
- hosts: tag_function_vault_node
  tasks: 

- name: terraform playbook
  import_playbook: terraform-install.yml
- name: vault playbook
  import_playbook: vault-install.yml
- name: aws cli playbook
  import_playbook: awscli-install.yml
- name: command prompt change
  import_playbook: commandPrompt.yml 