- hosts: dev-test 
  become: yes
  name: Vault Playbook
  tasks: 
    - name: install zip utility
      apt: 
        package: unzip
        state: present 
    - name: download vault zip files
      get_url:
        dest: /tmp/vault.zip
        url:  https://releases.hashicorp.com/vault/1.11.3/vault_1.11.3_linux_amd64.zip
    - name: unzip vault files 
      unarchive: 
        src: /tmp/vault.zip 
        dest: /usr/bin 
        remote_src: yes